Repository osulp/Scholars-Archive, pull requests merged in 2022-11, with the labels that each got.

#2412 Prepopulate the license only in Dataset
  app/views/datasets/edit_fields/_license.html.erb
Labels: Enhancement

#2414 Add in the new Fixity command
  lib/tasks/fixity_check.rake
Labels: Bug

#2418 Update timedate format based on feedback
  app/assets/stylesheets/osu.scss
  app/views/hyrax/base/_workflow_actions.html.erb
Labels: Enhancement

#2420 Add in pre-selected Copyright
  app/views/datasets/edit_fields/_rights_statement.html.erb
Labels: Enhancement

#2425 allow Sidekiq workers to fail gracefully
  build/entrypoint-sidekiq.sh
Labels: Bug, Priority: High, Infrastructure
